FROM odoo:latest

USER root
COPY init-odoo.sh /init-odoo.sh
RUN chmod +x /init-odoo.sh
# Copia el logo si existe (falla silenciosamente si no hay archivo)
COPY logo.png /logo.png
# El entrypoint arranca como root para poder corregir permisos del volumen
# y luego usa gosu para bajar al usuario odoo

ENTRYPOINT ["/init-odoo.sh"]
