db.url=jdbc:mysql://db_app:3306/clicktochef
db.user=root
db.password=adminDB

odoo.url=http://odoo:8069
odoo.db=clicktochefDB
odoo.user=clicktochef@clicktochef.com
odoo.password=clicktochef

server.port=5000
webserver.port=5001