db.url=jdbc:mysql://localhost:3306/clicktochef
db.user=root
db.password=adminDB

odoo.url=http://localhost:8069
odoo.db=clicktochef_odoo
odoo.user=tu_email@ejemplo.com
odoo.password=tu_password_o_api_key

server.port=5000